"""Configure Streamlit OIDC before the web server starts. Secrets stay local."""
import json
import os
from pathlib import Path
import sys
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]


def auth_config():
    keys = ('OIDC_CLIENT_ID','OIDC_CLIENT_SECRET','OIDC_COOKIE_SECRET')
    if not all(os.getenv(key) for key in keys):
        return None
    if len(os.environ['OIDC_COOKIE_SECRET']) < 32:
        raise ValueError('OIDC cookie secret must be at least 32 characters')
    redirect = os.getenv('OIDC_REDIRECT_URI','http://localhost:8501/oauth2callback')
    parsed = urlparse(redirect)
    if parsed.path != '/oauth2callback' or parsed.query or parsed.fragment:
        raise ValueError('Invalid OIDC callback URI')
    if os.getenv('DEPLOYMENT_ENV') == 'production' and parsed.scheme != 'https':
        raise ValueError('Production sign-in requires an HTTPS callback')
    if parsed.scheme not in {'http','https'} or not parsed.hostname:
        raise ValueError('Invalid OIDC callback URI')
    provider = os.getenv('OIDC_PROVIDER','google')
    if provider == 'google':
        metadata = 'https://accounts.google.com/.well-known/openid-configuration'
        kwargs = {'scope':'openid email profile','prompt':'select_account','hd':'uci.edu'}
    elif provider == 'microsoft':
        import uuid
        tenant = str(uuid.UUID(os.environ.get('OIDC_TENANT_ID','')))
        metadata = f'https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration'
        kwargs = {'scope':'openid email profile','prompt':'select_account'}
    else:
        raise ValueError('Unsupported OIDC provider')
    values = {'redirect_uri':redirect, 'cookie_secret':os.environ['OIDC_COOKIE_SECRET'],
              'client_id':os.environ['OIDC_CLIENT_ID'], 'client_secret':os.environ['OIDC_CLIENT_SECRET'],
              'server_metadata_url':metadata}
    lines = ['# Generated by ui/launch.py from server environment. Do not commit.','[auth]']
    lines += [f'{key} = {json.dumps(value)}' for key,value in values.items()]
    lines += ['client_kwargs = { '+', '.join(f'{key} = {json.dumps(value)}' for key,value in kwargs.items())+' }']
    return '\n'.join(lines)+'\n'


def main():
    from dotenv import load_dotenv
    load_dotenv(ROOT/'.env')
    if os.getenv('DEPLOYMENT_ENV') == 'production' and os.getenv('DOCUMIND_LOCAL_ADMIN','false').lower() == 'true':
        raise ValueError('Local admin bypass is forbidden in production')
    config = auth_config()
    if os.getenv('DEPLOYMENT_ENV') == 'production' and not config:
        raise ValueError('Configure verified UCI sign-in before production startup')
    if config:
        directory = ROOT/'.streamlit'
        directory.mkdir(exist_ok=True)
        path = directory/'secrets.toml'
        if path.exists() and not path.read_text(encoding='utf-8').startswith('# Generated by ui/launch.py'):
            raise ValueError('Existing manually configured secrets.toml was preserved; configure auth consistently before startup')
        path.write_text(config,encoding='utf-8')
        path.chmod(0o600)
    os.chdir(ROOT)
    os.execv(sys.executable,[sys.executable,'-m','streamlit','run','ui/app.py',
        '--server.address='+os.getenv('DOCUMIND_SERVER_ADDRESS','127.0.0.1'),
        '--server.port='+os.getenv('PORT','8501'),'--browser.gatherUsageStats=false',
        '--theme.primaryColor=#087f8c','--theme.backgroundColor=#f4f7fb',
        '--theme.secondaryBackgroundColor=#edf3f7','--theme.textColor=#16334c',
        '--theme.font=sans serif','--theme.base=light'])


if __name__ == '__main__':
    main()
